-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(datetime, 'HH24')) HOUR, COUNT(TO_CHAR(datetime, 'HH24')) COUNT
FROM ANIMAL_OUTS
WHERE TO_NUMBER(TO_CHAR(datetime, 'HH24')) BETWEEN 9 AND 19
GROUP BY TO_NUMBER(TO_CHAR(datetime, 'HH24'))
ORDER BY TO_NUMBER(TO_CHAR(datetime, 'HH24'))