-- 코드를 입력하세요
SELECT h.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR  c, CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE c.CAR_ID = h.CAR_ID
AND c.CAR_TYPE = '세단'
AND TO_CHAR(START_DATE, 'MM') = '10'
GROUP BY h.CAR_ID
ORDER BY h.CAR_ID DESC